### ISSUE TITLE
背景尺寸与容器尺寸间的比例的计算多余

### ISSUE THREAD

**Issue by bh-lay** [BoltDoggy/imgCenter#1]
背景尺寸与容器尺寸间的比例计算多余，因为纠结于`100% auto`和`auto 100%`结果很明显，就是`background-size:cover`，而`cover`这个属性值是'background-size'的基本属性。

**Comment by BoltDoggy** [comment]
感谢提醒，原谅小弟学艺不精。为了解决的这个比例计算，还绞尽脑汁想出利用了一个图片对象的实例化。

另，对于 src 中的图片改成透明的，有没有更好的实现方法，我是引入了一个像素的透明图片，感觉代码好多的样子，不知道会不会影响效率。

**Comment by bh-lay** [comment]
引用一像素图片是比较通用的方式，不会影响到html、css结构，目前来看应是最好的方式了。如果不是功能独立为组件，可以尝试改写dom，当然，这句是废话。
